function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-indigo-900 via-purple-900 to-pink-900 p-8 pt-20">
      <div className="max-w-4xl mx-auto bg-white/10 backdrop-blur-md rounded-2xl p-8 text-white">
        <h1 className="text-4xl font-bold text-pink-400 mb-6">Terms and Conditions</h1>
        <p className="text-white/70 mb-4">Last updated: May 2026</p>

        <div className="space-y-6">
          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">1. Acceptance of Terms</h2>
            <p className="text-white/80">
              By accessing and using TECHYA, you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">2. Description of Service</h2>
            <p className="text-white/80">
              TECHYA is an AI-powered virtual fairy companion that provides conversational interactions through voice and text.
              The service uses artificial intelligence to generate responses. The AI may not always provide accurate or perfect responses.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">3. User Conduct</h2>
            <p className="text-white/80">
              You agree NOT to use the service to:
              <ul className="list-disc ml-6 mt-2 space-y-1">
                <li>Upload or transmit any content that is illegal, harmful, or offensive</li>
                <li>Attempt to hack, reverse engineer, or disrupt the service</li>
                <li>Use the service for any illegal or unauthorized purpose</li>
                <li>Harass, threaten, or impersonate others</li>
              </ul>
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">4. Intellectual Property</h2>
            <p className="text-white/80">
              The content, design, and functionality of TECHYA are the intellectual property of Saumya Bisht.
              You may not copy, modify, distribute, or reproduce any part of this service without prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">5. Disclaimer of Warranties</h2>
            <p className="text-white/80">
              TECHYA is provided "as is" without any warranties, express or implied. We do not guarantee
              that the service will be uninterrupted, error-free, or completely secure. The AI responses are
              generated by machine learning and may not always be accurate, appropriate, or reliable.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">6. Limitation of Liability</h2>
            <p className="text-white/80">
              In no event shall Saumya Bisht or TECHYA be liable for any indirect, incidental, special,
              or consequential damages arising out of or in connection with your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">7. Privacy</h2>
            <p className="text-white/80">
              Your privacy is important to us. Please refer to our Privacy Policy for information on how we collect
              and use your data. By using TECHYA, you consent to the collection and use of information as described therein.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">8. Termination</h2>
            <p className="text-white/80">
              We reserve the right to terminate or suspend access to the service at any time without prior notice
              for any violation of these terms or for any other reason.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">9. Contact Information</h2>
            <p className="text-white/80">
              For any questions about these Terms and Conditions, please contact:
              <br /><br />
              <strong>Saumya Bisht</strong>
              <br />Founder & Creator of TECHYA (linkedin.com/in/saumya-bisht)
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-yellow-300 mb-3">10. About the Founder</h2>
            <p className="text-white/80">
              TECHYA was created and developed by <strong>Saumya Bisht</strong>.
              Saumya is the sole owner, creator, and operator of this service. All rights reserved.
            </p>
          </section>
        </div>

        <div className="mt-8 text-center space-x-4">
          <a href="/privacy" className="text-pink-400 hover:underline text-lg">Privacy Policy</a>
          <span className="text-white/50">|</span>
          <a href="/" className="text-pink-400 hover:underline text-lg">← Back to TECHYA</a>
        </div>
      </div>
    </div>
  )
}

export default TermsAndConditions